---
title: "Uber Take Home"
author: "Jeffrey Uslan"
date: "November 1, 2015"
output: word_document
---
```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(rpart)
library(randomForest)
library(MASS)
library(zoo)
library(caret)
library(pander)
```

```{r}
 load(file="uber_test_data.rda")
```


```{r}
data=tbl_df(uber_unlist)
data$trips_in_first_30_days=as.numeric(as.character(data$trips_in_first_30_days))
data$signup_date=as.Date(data$signup_date)
data$avg_rating_of_driver=as.numeric(as.character(data$avg_rating_of_driver))
data$avg_surge=as.numeric(as.character(data$avg_surge))
data$last_trip_date=as.Date(data$last_trip_date)
data$surge_pct=as.numeric(as.character(data$surge_pct))
data$weekday_pct=as.numeric(as.character(data$weekday_pct))
data$avg_dist=as.numeric(as.character(data$avg_dist))
data$avg_rating_by_driver=as.numeric(as.character(data$avg_rating_by_driver))
```

```{r}
numeric_data_inds=sapply(data,is.numeric)
cat_data_inds=!sapply(data,is.numeric)

#tabulations of categorical data
pander(data %>% group_by(city) %>% summarise(Count=n()))
pander(data %>% group_by(phone) %>% summarise(Count=n()))
pander(data %>% group_by(uber_black_user) %>% summarise(Count=n()))
```

```{r}
#generating retained variable
data$retained=0
data$retained[which(data$trips_in_first_30_days>0)]=1
mean(data$retained,na.rm=TRUE)


data$retained=as.factor(data$retained)
data %>% group_by(retained) %>% summarise(Count=n())
```

#numeric exploration
```{r}
data=na.omit(data)



pander(data %>% group_by(retained) %>% summarise(Distance=mean(avg_dist),Weekday=mean(weekday_pct),                                       Passenger=mean(avg_rating_by_driver),Driver=mean(avg_rating_of_driver),
                                          Surges=mean(avg_surge)))

ggplot(data)+geom_density(aes(x=avg_dist))+theme_bw()+facet_grid(retained~.)+
  ggtitle("Drive Distance")+xlab("Miles")+ylab("Density")


ggplot(data)+geom_density(aes(x=weekday_pct))+theme_bw()+facet_grid(retained~.)+
  ggtitle("Weekday Driving")+xlab("Percent")+ylab("Density")

ggplot(data)+geom_density(aes(x=avg_rating_by_driver))+ theme_bw()+facet_grid(retained~.)+ggtitle("Passenger Ratings")+xlab("Rating")+ylab("Density")


ggplot(data)+geom_density(aes(x=avg_rating_of_driver))+  theme_bw()+facet_grid(retained~.)+ggtitle("Driver Ratings")+xlab("Rating")+ylab("Density")

ggplot(data)+geom_density(aes(x=avg_surge))+  
  theme_bw()+facet_grid(retained~.)+ggtitle("Driver Ratings")+xlab("Rating")+ylab("Density")

ggplot(data)+geom_density(aes(x=surge_pct))+  
  theme_bw()+facet_grid(retained~.)+ggtitle("Driver Ratings")+xlab("Rating")+ylab("Density")










```

#covariates
```{r}

inTrain = createDataPartition(y=data$retained, p = .6)[[1]]
training = data[ inTrain,]
testing = data[-inTrain,]

modFit <- randomForest(retained ~city + phone +uber_black_user + avg_rating_of_driver +
  avg_surge+ surge_pct + weekday_pct +avg_dist +avg_rating_by_driver ,data=training)


train_pred=predict(modFit,newdata= training, type = "response")
confusionMatrix(training$retained,train_pred )


test_pred=predict(modFit,newdata= testing, type = "response")
confusionMatrix(testing$retained,test_pred)


varImpPlot(modFit,main="Variable Importance")

```


